module.exports = {
  CSK: ['Ruturaj Gaikwad', 'MS Dhoni', 'Sanju Samson', 'Dewald Brevis', 'Ayush Mhatre', 'Kartik Sharma', 'Sarfaraz Khan', 'Urvil Patel', 'Anshul Kamboj', 'Jamie Overton', 'Ramakrishna Ghosh', 'Prashant Veer', 'Matthew William Short', 'Aman Khan', 'Zak Foulkes', 'Shivam Dube', 'Khaleel Ahmed', 'Noor Ahmad', 'Mukesh Choudhary', 'Nathan Ellis', 'Shreyas Gopal', 'Gurjapneet Singh', 'Akeal Hosein', 'Matt Henry', 'Rahul Chahar'],
  DC: ['KL Rahul', 'Karun Nair', 'David Miller', 'Ben Duckett', 'Pathum Nissanka', 'Sahil Parakh', 'Prithvi Shaw', 'Abishek Porel', 'Tristan Stubbs', 'Axar Patel', 'Sameer Rizvi', 'Ashutosh Sharma', 'Vipraj Nigam', 'Ajay Mandal', 'Tripurana Vijay', 'Madhav Tiwari', 'Auqib Dar', 'Nitish Rana', 'Mitchell Starc', 'T. Natarajan', 'Mukesh Kumar', 'Dushmantha Chameera', 'Lungisani Ngidi', 'Kyle Jamieson', 'Kuldeep Yadav'],
  GT: ['Shubman Gill', 'Jos Buttler', 'Kumar Kushagra', 'Anuj Rawat', 'Tom Banton', 'Glenn Phillips', 'Nishant Sindhu', 'Washington Sundar', 'Mohd. Arshad Khan', 'Sai Kishore', 'Jayant Yadav', 'Jason Holder', 'Sai Sudharsan', 'Shahrukh Khan', 'Kagiso Rabada', 'Mohammed Siraj', 'Prasidh Krishna', 'Manav Suthar', 'Gurnoor Singh Brar', 'Ishant Sharma', 'Ashok Sharma', 'Prithvi Raj Yarra', 'Luke Wood', 'Rahul Tewatia', 'Rashid Khan'],
  KKR: ['Ajinkya Rahane', 'Rinku Singh', 'Angkrish Raghuvanshi', 'Manish Pandey', 'Cameron Green', 'Finn Allen', 'Tejasvi Singh', 'Rahul Tripathi', 'Tim Seifert', 'Rovman Powell', 'Anukul Roy', 'Sarthak Ranjan', 'Daksh Kamra', 'Rachin Ravindra', 'Ramandeep Singh', 'Blessing Muzarabani', 'Vaibhav Arora', 'Matheesha Pathirana', 'Kartik Tyagi', 'Prashant Solanki', 'Akash Deep', 'Harshit Rana', 'Umran Malik', 'Sunil Narine', 'Varun Chakaravarthy'],
  LSG: ['Rishabh Pant', 'Aiden Markram', 'Himmat Singh', 'Matthew Breetzke', 'Mukul Choudhary', 'Akshat Raghuwanshi', 'Josh Inglis', 'Nicholas Pooran', 'Mitchell Marsh', 'Abdul Samad', 'Shahbaz Ahamad', 'Arshin Kulkarni', 'Wanindu Hasaranga', 'Ayush Badoni', 'Mohammad Shami', 'Avesh Khan', 'M. Siddharth', 'Digvesh Singh', 'Akash Singh', 'Prince Yadav', 'Arjun Tendulkar', 'Anrich Nortje', 'Naman Tiwari', 'Mayank Yadav', 'Mohsin Khan'],
  MI: ['Rohit Sharma', 'Surya Kumar Yadav', 'Robin Minz', 'Sherfane Rutherford', 'Ryan Rickelton', 'Quinton de Kock', 'Danish Malewar', 'N. Tilak Varma', 'Hardik Pandya', 'Naman Dhir', 'Mitchell Santner', 'Raj Angad Bawa', 'Atharva Ankolekar', 'Mayank Rawat', 'Corbin Bosch', 'Will Jacks', 'Shardul Thakur', 'Trent Boult', 'Mayank Markande', 'Deepak Chahar', 'Ashwani Kumar', 'Raghu Sharma', 'Mohammad Izhar', 'Allah Ghazanfar', 'Jasprit Bumrah'],
  PBKS: ['Shreyas Iyer', 'Nehal Wadhera', 'Vishnu Vinod', 'Harnoor Pannu', 'Pyla Avinash', 'Prabhsimran Singh', 'Shashank Singh', 'Marcus Stoinis', 'Harpreet Brar', 'Marco Jansen', 'Azmatullah Omarzai', 'Priyansh Arya', 'Musheer Khan', 'Suryansh Shedge', 'Mitch Owen', 'Cooper Connolly', 'Ben Dwarshuis', 'Arshdeep Singh', 'Yuzvendra Chahal', 'Vyshak Vijaykumar', 'Yash Thakur', 'Xavier Bartlett', 'Pravin Dubey', 'Vishal Nishad', 'Lockie Ferguson'],
  RR: ['Riyan Parag', 'Shubham Dubey', 'Vaibhav Suryavanshi', 'Donovan Ferreira', 'Lhuan-dre Pretorius', 'Ravi Singh', 'Aman Rao Perala', 'Shimron Hetmyer', 'Yashasvi Jaiswal', 'Dhruv Jurel', 'Yudhvir Singh Charak', 'Ravindra Jadeja', 'Sam Curran', 'Jofra Archer', 'Tushar Deshpande', 'Kwena Maphaka', 'Ravi Bishnoi', 'Sushant Mishra', 'Yash Raj Punja', 'Vignesh Puthur', 'Brijesh Sharma', 'Adam Milne', 'Kuldeep Sen', 'Sandeep Sharma', 'Nandre Burger'],
  RCB: ['Rajat Patidar', 'Devdutt Padikkal', 'Virat Kohli', 'Phil Salt', 'Jitesh Sharma', 'Jordan Cox', 'Krunal Pandya', 'Swapnil Singh', 'Tim David', 'Romario Shepherd', 'Jacob Bethell', 'Venkatesh Iyer', 'Satvik Deswal', 'Mangesh Yadav', 'Vicky Ostwal', 'Vihaan Malhotra', 'Kanishk Chouhan', 'Josh Hazlewood', 'Rasikh Dar', 'Suyash Sharma', 'Bhuvneshwar Kumar', 'Nuwan Thushara', 'Abhinandan Singh', 'Jacob Duffy', 'Yash Dayal'],
  SRH: ['Ishan Kishan', 'Aniket Verma', 'Smaran Ravichandran', 'Salil Arora', 'Heinrich Klaasen', 'Travis Head', 'Harshal Patel', 'Kamindu Mendis', 'Harsh Dubey', 'Brydon Carse', 'Shivang Kumar', 'Krains Fuletra', 'Liam Livingstone', 'Jack Edwards', 'Abhishek Sharma', 'Nitish Kumar Reddy', 'Pat Cummins', 'Zeeshan Ansari', 'Jaydev Unadkat', 'Eshan Malinga', 'Sakib Hussain', 'Onkar Tarmale', 'Amit Kumar', 'Praful Hinge', 'Shivam Mavi']
};
